server:
  uri: "ws://talk.deepwiser.com:8999/ws"
  login_url: "http://47.99.146.156:8889/user/v2/login"
  salt_url: "http://47.99.146.156:8889/user/v2/login/code/"

user:
  username: "<your username (phone number)>"
  password: "<your password>"

constants:
  password_salt: "ZT0G7EwHzgaQMzEJ"
  headers:
    Content-Type: "application/json; charset=utf-8"
    Host: "47.99.146.156:8889"
    Connection: "Keep-Alive"
    User-Agent: "okhttp/3.8.0"

message:
  start_byte: 0x02
  version: 0x01
  login_type: 0x05
  end_byte: 0x03

command:
  chat_id: "0001d81e0ec0d183"
  to_cust_id: "000200000c2a3561"
  addr: 0x1011
  data_type: 0x00
  data: 1
  afn: 0x01
  time_wait: 1

